"""init schema

Revision ID: 2051fbdf88f8
Revises: 
Create Date: 2017-08-06 18:58:09.915791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2051fbdf88f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
